domains:
  - domain_name: pelsabr.akadns.net    # domain to collect from (list)
    properties:
      - property_name: prod      # property config from which to collect traffic metrics (list)
        datacenter:
          - 3131                          # filter on datacenter id (list)

    datacenters:                          
      - datacenter_id: 3134               # datacenter config from which to collect traffic metrics (list)
      - datacenter_id: 3135               # datacenter config from which to collect traffic metrics (list)
      - datacenter_id: 3136               # datacenter config from which to collect traffic metrics (list)
      - datacenter_id: 3137               # datacenter config from which to collect traffic metrics (list)
      
    liveness_tests:
      - property_name: prod      # property config frm which to collect liveness test failures

summary_window: 2d              # # [m]ins, [h]ours, [d]ays. Default: 2d
prefill_window: 1h              # # [m]ins, [h]ours, [d]ays. Default: 10m
timestamp_label: false          # Creates time series with traffic timestamp as label
traffic_timestamp: false        # Create time series with traffic timestamp. Default: true

